# Generated by Django 4.2.30 on 2026-09-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.CharField(max_length=50, unique=True)),
                ("location_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemBEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_id", models.CharField(max_length=100, unique=True)),
                ("record_ref", models.CharField(blank=True, max_length=100)),
                (
                    "normalized_record_ref",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("recorded_on", models.CharField(blank=True, max_length=100)),
                ("value", models.CharField(blank=True, max_length=100)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("raw_data", models.JSONField(default=dict)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_b_entries",
                        to="reconciliation.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=100, unique=True)),
                ("event_date", models.CharField(blank=True, max_length=100)),
                ("category_code", models.CharField(blank=True, max_length=100)),
                ("actor_id", models.CharField(blank=True, max_length=100)),
                ("base_value", models.CharField(blank=True, max_length=100)),
                ("adjustment", models.CharField(blank=True, max_length=100)),
                ("total_value", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("raw_data", models.JSONField(default=dict)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_a_records",
                        to="reconciliation.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="reconciliation.organization",
            ),
        ),
    ]
